### PR TITLE
Upgrade to ProtoBuf 0.9 and make TensorBoardLogger threadsafe

### PR DESCRIPTION
**Pull request by PhilipVinc**
cc @jbaron

This PR adds a new gen/ subfolder with scripts and instructions to generate protbuf jl files, and regenerate them so they benefit by the new protobuf.jl version.

I have to cleanup a bit the generated files, because I think I'm importing lots of useless stuff, but that should not be a problem and can be left for later...

@jbaron can you tell me if this fixes your problems?

Everything should work except for deserialization ATM.

### CODE REVIEW

**Comment by jbaron** [comment]
Just a quick question: I should add this version to my project with "add https://github.com/PhilipVinc/TensorBoardLogger.jl/tree/threadsafe" and then test again, right?

**Comment by jbaron** [comment]
I get a load error if I add the the threadsafe branch. It seems to add right versions but when I run my test script I get the error, Ssee below (defect.jl is my simple test script to reproduce the error).

> 
> (Quanta) pkg> add https://github.com/PhilipVinc/TensorBoardLogger.jl#threadsafe
>     Cloning git-repo `https://github.com/PhilipVinc/TensorBoardLogger.jl`
>    Updating git-repo `https://github.com/PhilipVinc/TensorBoardLogger.jl`
>    Updating registry at `~/.julia/registries/General`
> ######################################################################## 100,0%
>   Resolving package versions...
>   Installed ProtoBuf ─ v0.9.0
> Updating `~/dev/tmp/Quanta.jl/Project.toml`
>   [899adc3e] + TensorBoardLogger v0.1.11 `https://github.com/PhilipVinc/TensorBoardLogger.jl#threadsafe`
> Updating `~/dev/tmp/Quanta.jl/Manifest.toml`
>   [3349acd9] ↑ ProtoBuf v0.8.0 ⇒ v0.9.0
>   [899adc3e] ~ TensorBoardLogger v0.1.11 ⇒ v0.1.11 `https://github.com/PhilipVinc/TensorBoardLogger.jl#threadsafe`
> 
> (Quanta) pkg> 
> peter@Smarty:~/dev/tmp/Quanta.jl$ julia --project=. test/defect.jl
> ERROR: LoadError: could not open file /home/peter/.julia/packages/TensorBoardLogger/WOXwJ/src/protojl/TensorBoard/tensorboard.jl
> Stacktrace:
>  [1] include(::Function, ::Module, ::String) at ./Base.jl:380
>  [2] include at ./Base.jl:368 [inlined]
>  [3] include(::String) at /home/peter/.julia/packages/TensorBoardLogger/WOXwJ/src/TensorBoardLogger.jl:1
>  [4] top-level scope at /home/peter/.julia/packages/TensorBoardLogger/WOXwJ/src/TensorBoardLogger.jl:28
>  [5] include(::Function, ::Module, ::String) at ./Base.jl:380
>  [6] include(::Module, ::String) at ./Base.jl:368
>  [7] top-level scope at none:2
>  [8] eval at ./boot.jl:331 [inlined]
>  [9] eval(::Expr) at ./client.jl:467
>  [10] top-level scope at ./none:3
>

**Comment by PhilipVinc** [comment]
Dammit. Mac not being case-sensitive always bites me.
It should work now.

(Yes, `]add https://github.com/PhilipVinc/TensorBoardLogger.jl#threadsafe` is exactly right)

**Comment by PhilipVinc** [comment]
@jbaron Could you test again?

**Comment by jbaron** [comment]
No more errors :) The following test is running fine (which was failing int he old version):


```
function run_parallel()  
    
    Threads.@threads for i in 1:20
        logdir = "runs/walkforward_$(i)"   
        logger = TBLogger(logdir)
        for j in 1:1000
            logmetric(logger, :dummy, 12.0, j, DateTime(2020))
        end
    end

end

@time run_parallel()
```

Thanks for fix !!!

**Comment by PhilipVinc** [comment]
Great.

it will take a while to land this in a release because I need a few Bugfixes on ProtoBuf. Moreover, the last version does not really support v1.0 so I might be obliged to drop support for that version.

This branch seems like it should work (minus de-serialization, which needs the bugfixes).
If you start use it for a bit and report back in a few days if you have (or not) any problem I'd appreciate it. 
I don't have time to do it myself..

**Comment by jbaron** [comment]
I'll keep this branch for now in my project and if I encounter any problems I'll let you know.

**Comment by jbaron** [comment]
Just to let you know, in the past few days I didn't encounter any multi-thread issues (or any other issues for that matter). I do however use not all functionality that this package has to offer, mostly I call the lower level API's to create summaries and then log them.

**Pull request merged**
