### PR TITLE
add Flux example

### PR DESCRIPTION
**Pull request by shashikdm**

### CODE REVIEW

**Comment by shashikdm** [comment]
#37 does this look alright?

**Comment by PhilipVinc** [comment]
Can you just check that this runs in a reasonable time (max ~minute) so that people can see the result? Batch size=6k seems big to me.

**Comment by oxinabox** [comment]
Can we link it in the docs and include a screenshot?
Is ther a way to do some kind of _include the text of this file_ into the built documentation with Documentor.jl ?

**Comment by shashikdm** [comment]
> Can you just check that this runs in a reasonable time (max ~minute) so that people can see the result? Batch size=6k seems big to me.

I have made the model simple and changed batch size to 100. Now it is running in my local machine smoothly.

**Comment by PhilipVinc** [comment]
> Can we link it in the docs and include a screenshot?
> Is ther a way to do some kind of _include the text of this file_ into the built documentation with Documentor.jl ?

What do you mean exactly? 
Like upload the notebook and include it in the docs?

**Comment by oxinabox** [comment]
Look at the Optim example.

https://philipvinc.github.io/TensorBoardLogger.jl/dev/examples/optim/

**Comment by PhilipVinc** [comment]
Ah ok. So of course we can (and we should).

**Pull request merged**
