### PR TITLE
Fix set_step_increment!

### PR DESCRIPTION
**Pull request by ToucheSir**
Was incorrectly setting the global step instead.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Wow, thanks. 
Could you also bump the minor version so I merge and tag a new release?

Thanks!

**Comment by ToucheSir** [comment]
That was fast! Just to clarify, would you like 0.2.0 or 0.1.12?

**Comment by PhilipVinc** [comment]
0.1.12

**Comment by ToucheSir** [comment]
Done. I must've misread the previous version, it should be 0.1.11 now :)

**Pull request merged**
