### PR TITLE
Add show to `TBLogger` object

### PR DESCRIPTION
**Pull request by PhilipVinc**
Added a show method to `TBLogger`

### CODE REVIEW

**Comment by oxinabox** [comment]
I beleive you have defined these backwards.
 - `show` should be parsable julia code (like what you have defined `print`) to be. 
 - `print` can be human readable description of thing (like what you have defined `show` to be)

See discussion in https://github.com/JuliaLang/julia/pull/30757

**Comment by PhilipVinc** [comment]
Thanks for the clarifying issue, I always had some confusion among those...

If I got it right, I should only declare a `show(io, ::TBLogger)` returning valid Julia code and a 
`show(io, mime::MIME"text/plain", ::TBLogger)` printing the pretty stuff. I should not declare `print`.

**Comment by oxinabox** [comment]
maybe?

**Comment by PhilipVinc** [comment]
At least, according to the docs in the current master, `print` should be overloaded only if you want a minimal representation. I'm not sure what a minimal representation would be, so for the moment I would keep it like that.

https://docs.julialang.org/en/v1.3-dev/manual/types/#man-custom-pretty-printing-1

and to this [comment](https://github.com/JuliaLang/julia/pull/30757#issuecomment-456925881)
> * minimal/canonical representation: `print`. `string` gives a string of its output.
> * parseable (if possible) representation of any value: `show(io, x)`. `repr(x)` gives a string of its output.
> * pretty display format for any value: `show(io, mime, x)`. `repr(mime, x)` gives a string of its output.

If there are no objections I'll merge this.

**Comment by oxinabox** [comment]
sounds right to me

**Pull request merged**
