### PR TITLE
Add Base.close for TBLogger

### LINKED ISSUE #108: Support `Base.close`?
I am using a machine with a network file system, and I am following a REPL-based dev flow. When I run the code to initialize the `TBLogger` (for a second time), I get a "resource busy" message from the OS.

It would be nice to support `Base.close(::TBLogger)` which performs the first part of `reset!(::TBLogger)` by releasing all the file handles.

### PR DESCRIPTION
**Pull request by darsnack**
Fixes #108

### CODE REVIEW

**Comment by PhilipVinc** [comment]
should we maybe add a finaliser to `TBLogger` that calls close?

**Comment by darsnack** [comment]
Good idea, just added it.

**Comment by darsnack** [comment]
@PhilipVinc I think this is good now?

**Comment by PhilipVinc** [comment]
looks great! thanks

**Review by PhilipVinc — APPROVED** [review]

**Pull request merged**
