### PR TITLE
Add events function to helpers.jl

### PR DESCRIPTION
**Pull request by VaiTon**

### CODE REVIEW

**Comment by oxinabox** [comment]
Can this have unit tests, and a more informativative docstring?

**Comment by VaiTon** [comment]
@oxinabox about the tests, could you point me to where should I add them? About the docstring, what else can be added? I think it's pretty clear as it is.

**Comment by oxinabox** [comment]
add the tests in a new testset at the bottom of  https://github.com/JuliaLogging/TensorBoardLogger.jl/blob/master/test/test_TBLogger.jl#L126

add a sentence saying what an event is, and perhaps another saying why you might use this function.

**Comment by VaiTon** [comment]
@oxinabox done!

**Comment by oxinabox** [comment]
thanks

**Pull request merged**
