### PR TITLE
Fix bug for tags that end in non-ascii chars

### PR DESCRIPTION
**Pull request by JobJob**

### CODE REVIEW

**Comment by PhilipVinc** [comment]
can you add a test for the behaviour that is fixed?

**Comment by JobJob** [comment]
ehhh not really atm sorry no time. You can not merge if you want until some future time that I may find to provide one, but that day may never come 😬  Thanks for the package!

**Comment by JobJob** [comment]
Or you can get crazy and take a chance and merge 😄

**Comment by JobJob** [comment]
Forgot to mention the scenario this fixes: tblogging with e.g. the tag "μff" then using TensorBoardLogger.map_summaries throws an error without this.

Minimal trigger

```julia
using TensorBoardLogger: tags_match_re_im

tags_match_re_im("μff", "new_tag")
```

Thanks! 🙏 

(edited to show clearer example)

**Pull request merged**
